$(eval $(call addlib,apprsaverify))
APPRSAVERIFY_SRCS-y += $(APPRSAVERIFY_BASE)/io.c
APPRSAVERIFY_SRCS-y += $(APPRSAVERIFY_BASE)/rsa-verify.c
APPRSAVERIFY_SRCS-y += $(APPRSAVERIFY_BASE)/read_rsa_key.c
