$(eval $(call addlib,apprsaencrypt))
APPRSAENCRYPT_SRCS-y += $(APPRSAENCRYPT_BASE)/io.c
APPRSAENCRYPT_SRCS-y += $(APPRSAENCRYPT_BASE)/rsa-encrypt.c
APPRSAENCRYPT_SRCS-y += $(APPRSAENCRYPT_BASE)/read_rsa_key.c
