$(eval $(call addlib,apprsadecrypt))
APPRSADECRYPT_SRCS-y += $(APPRSADECRYPT_BASE)/io.c
APPRSADECRYPT_SRCS-y += $(APPRSADECRYPT_BASE)/rsa-decrypt.c
APPRSADECRYPT_SRCS-y += $(APPRSADECRYPT_BASE)/read_rsa_key.c
